site:
  title: TIP-3 Docs
  url: https://docs.tip.com
  start_page: ROOT::contracts.adoc
content:
  sources:
    - url: .
      branches: HEAD
      start_path: components/home
    # - url: https://github.com/Cyace84/tip3
    #   branches: tests
    #   start_path: docs
ui:
  bundle:
    url: ./ui/theme
asciidoc:
  attributes:
    idprefix: ''
antora:
  extensions:
    - require: './lunr-tokenizer'
    - require: '@antora/lunr-extension'
      index_latest_only: true
